Pools summary EP
spectrum-finance/ergo-dex-backend pull request #65
Opened 2022-10-19 20:07 UTC by semyonoskin

2022-10-20 09:05 UTC, GusevTimofey requested changes

2022-10-20 09:05 UTC, GusevTimofey commented on modules/markets-api/src/main/scala/org/ergoplatform/dex/markets/api/v1/endpoints/AmmStatsEndpoints.scala
> +      .description("Get summary by every known pool")
write here about TVL sorting

2022-10-20 09:05 UTC, GusevTimofey commented on modules/markets-api/src/main/scala/org/ergoplatform/dex/markets/db/sql/AnalyticsSql.scala
> +    val assetJoin =
fmt

2022-10-20 09:05 UTC, GusevTimofey commented on modules/markets-api/src/main/scala/org/ergoplatform/dex/markets/repositories/Pools.scala
> +    def snapshots(hasTicker: Boolean): Mid[F, List[PoolSnapshot]] =
add hasTicker into trace log

2022-10-20 12:34 UTC, semyonoskin commented on modules/markets-api/src/main/scala/org/ergoplatform/dex/markets/api/v1/services/AmmStats.scala
> +                    .setScale(6),
This is a method of RealPrice class : 

`@newtype case class RealPrice(value: BigDecimal) {
    def setScale(scale: Int): RealPrice = RealPrice(value.setScale(scale, RoundingMode.HALF_UP))
  }`

2022-10-20 12:36 UTC, GusevTimofey commented on modules/markets-api/src/main/scala/org/ergoplatform/dex/markets/api/v1/services/AmmStats.scala
> +                    .setScale(6),
My bad

2022-10-25 07:31 UTC, GusevTimofey approved these changes

2022-10-25 07:33 UTC, merged